<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\data\**\*.csv" LinkBase="data" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MaintPlan.Core\MaintPlan.Core.csproj" />
    <ProjectReference Include="..\..\src\MaintPlan.IO\MaintPlan.IO.csproj" />
    <ProjectReference Include="..\..\src\MaintPlan.Cli\MaintPlan.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

</Project>
